// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NoteService is the bridge between the frontend and the data layer. Wails
 * generates JavaScript bindings for every exported method here, which is why the
 * signatures use plain types that survive a trip through JSON.
 * 
 * It holds no SQL of its own; every query lives in internal/store.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";

/**
 * AllTags returns every tag in use, for autocomplete.
 * @returns {$CancellablePromise<string[]>}
 */
export function AllTags() {
    return $Call.ByID(1863405505).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Create saves a new note and returns its id.
 * @param {store$0.NoteInput} $in
 * @returns {$CancellablePromise<number>}
 */
export function Create($in) {
    return $Call.ByID(955216145, $in);
}

/**
 * DataDir returns the folder holding the database and attachments, so the UI can
 * show the user where their data is and therefore what to back up.
 * @returns {$CancellablePromise<string>}
 */
export function DataDir() {
    return $Call.ByID(1127397952);
}

/**
 * Delete soft-deletes a note; Restore brings it back.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(3620747094, id);
}

/**
 * ExportBackup writes a consistent copy of the database to path, safe to run
 * while the app is in use.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function ExportBackup(path) {
    return $Call.ByID(1188286669, path);
}

/**
 * Get returns a single note.
 * @param {number} id
 * @returns {$CancellablePromise<store$0.Note>}
 */
export function Get(id) {
    return $Call.ByID(2869398643, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * List returns notes for the sidebar, most recently updated first.
 * @param {number} limit
 * @param {number} offset
 * @returns {$CancellablePromise<store$0.Summary[]>}
 */
export function List(limit, offset) {
    return $Call.ByID(1156407021, limit, offset).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RenderMarkdown converts a note body to HTML for the preview pane.
 * 
 * Rendering happens in Go rather than in the webview so that the escaping rules
 * are decided in one place: raw HTML in a note is shown as text, and link
 * schemes are checked. See internal/markdown.
 * @param {string} source
 * @returns {$CancellablePromise<string>}
 */
export function RenderMarkdown(source) {
    return $Call.ByID(201050328, source);
}

/**
 * Restore undoes a Delete.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function Restore(id) {
    return $Call.ByID(4194717781, id);
}

/**
 * Revisions returns a note's superseded versions, newest first. Nothing in the
 * interface calls this; it exists so that text replaced by a careless edit is
 * still reachable, which for a months-old finding is the difference between a
 * mistake and a loss.
 * @param {number} id
 * @returns {$CancellablePromise<store$0.Revision[]>}
 */
export function Revisions(id) {
    return $Call.ByID(825284677, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Search finds notes matching query. Tokens of three or more characters are
 * matched as substrings against the full-text index; shorter ones, which that
 * index cannot hold, fall back to a scan. See store.Search.
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<store$0.Hit[]>}
 */
export function Search(query, limit) {
    return $Call.ByID(2632012349, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * Update saves changes to an existing note, preserving the previous text as a
 * revision.
 * @param {number} id
 * @param {store$0.NoteInput} $in
 * @returns {$CancellablePromise<void>}
 */
export function Update(id, $in) {
    return $Call.ByID(3018467456, id, $in);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = store$0.Note.createFrom;
const $$createType2 = store$0.Summary.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = store$0.Revision.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = store$0.Hit.createFrom;
const $$createType7 = $Create.Array($$createType6);
