// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Hit is one search result.
 * 
 * Title and Excerpt are carried as segments rather than HTML; see the Segment
 * doc comment for why this package never emits markup.
 */
export class Hit {
    /**
     * Creates a new Hit instance.
     * @param {Partial<Hit>} [$$source = {}] - The source object to create the Hit.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("titleSegments" in $$source)) {
            /**
             * @member
             * @type {Segment[]}
             */
            this["titleSegments"] = [];
        }
        if (!("excerpt" in $$source)) {
            /**
             * @member
             * @type {Segment[]}
             */
            this["excerpt"] = [];
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["updatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Hit instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Hit}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("titleSegments" in $$parsedSource) {
            $$parsedSource["titleSegments"] = $$createField2_0($$parsedSource["titleSegments"]);
        }
        if ("excerpt" in $$parsedSource) {
            $$parsedSource["excerpt"] = $$createField3_0($$parsedSource["excerpt"]);
        }
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        if ("updatedAt" in $$parsedSource) {
            $$parsedSource["updatedAt"] = $$createField5_0($$parsedSource["updatedAt"]);
        }
        return new Hit(/** @type {Partial<Hit>} */($$parsedSource));
    }
}

/**
 * Note is a single logbook entry.
 */
export class Note {
    /**
     * Creates a new Note instance.
     * @param {Partial<Note>} [$$source = {}] - The source object to create the Note.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * markdown
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("instrument" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["instrument"] = "";
        }
        if (!("dut" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dut"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["createdAt"] = new Date("0001-01-01T00:00:00.000Z");
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["updatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Note}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $Create.DateFromTime;
        const $$createField8_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField6_0($$parsedSource["tags"]);
        }
        if ("createdAt" in $$parsedSource) {
            $$parsedSource["createdAt"] = $$createField7_0($$parsedSource["createdAt"]);
        }
        if ("updatedAt" in $$parsedSource) {
            $$parsedSource["updatedAt"] = $$createField8_0($$parsedSource["updatedAt"]);
        }
        return new Note(/** @type {Partial<Note>} */($$parsedSource));
    }
}

/**
 * NoteInput carries the writable fields of a note. It is separate from Note so
 * that callers cannot pretend to set an id or a timestamp.
 */
export class NoteInput {
    /**
     * Creates a new NoteInput instance.
     * @param {Partial<NoteInput>} [$$source = {}] - The source object to create the NoteInput.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("instrument" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["instrument"] = "";
        }
        if (!("dut" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dut"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NoteInput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NoteInput}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField5_0($$parsedSource["tags"]);
        }
        return new NoteInput(/** @type {Partial<NoteInput>} */($$parsedSource));
    }
}

/**
 * Revision is a superseded version of a note's text.
 */
export class Revision {
    /**
     * Creates a new Revision instance.
     * @param {Partial<Revision>} [$$source = {}] - The source object to create the Revision.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("noteId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["noteId"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("replacedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["replacedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Revision instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Revision}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("replacedAt" in $$parsedSource) {
            $$parsedSource["replacedAt"] = $$createField4_0($$parsedSource["replacedAt"]);
        }
        return new Revision(/** @type {Partial<Revision>} */($$parsedSource));
    }
}

/**
 * Segment is a run of excerpt text that either matched the query or did not.
 * 
 * Search results are returned as segments rather than as pre-built HTML for two
 * reasons: this package has no business generating markup, and a note body is
 * arbitrary user text, so handing the frontend a string containing <mark> tags
 * would mean deciding what to escape here and hoping the UI agrees. With
 * segments the UI escapes every Text it receives and wraps the matching ones,
 * and note content can never become markup.
 */
export class Segment {
    /**
     * Creates a new Segment instance.
     * @param {Partial<Segment>} [$$source = {}] - The source object to create the Segment.
     */
    constructor($$source = {}) {
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("match" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["match"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Segment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Segment}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Segment(/** @type {Partial<Segment>} */($$parsedSource));
    }
}

/**
 * Summary is the reduced form used for the note list, where the full body would
 * be wasted bandwidth.
 */
export class Summary {
    /**
     * Creates a new Summary instance.
     * @param {Partial<Summary>} [$$source = {}] - The source object to create the Summary.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("excerpt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["excerpt"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {Date}
             */
            this["updatedAt"] = new Date("0001-01-01T00:00:00.000Z");
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Summary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Summary}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $Create.DateFromTime;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        if ("updatedAt" in $$parsedSource) {
            $$parsedSource["updatedAt"] = $$createField4_0($$parsedSource["updatedAt"]);
        }
        return new Summary(/** @type {Partial<Summary>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Segment.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
